DROP TABLE IF EXISTS SHOP ;
CREATE TABLE SHOP (  
id INTEGER AUTO_INCREMENT PRIMARY KEY,  
name VARCHAR(100) NOT NULL,  
domain VARCHAR(100) NOT NULL  
);  
 
DROP TABLE IF EXISTS PRODUCT ;
CREATE TABLE PRODUCT (  
id INTEGER  AUTO_INCREMENT PRIMARY KEY,  
counts INTEGER NOT NULL ,
name VARCHAR(100) NOT NULL 
);  

